config/routes.rb
Loudius::Application.routes.draw do
  get 'login' => 'sessions#new'
  get 'reg' => 'users#new'

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :detect_browser

  def bg_img
    @rnd = (rand(9)+1)

    if @rnd == 1
      @bg_image = '1.jpg'
      @bg_text = 'Sunset, Kafue National Park'
      @bg_username = 'Patricia Chibaye'
    elsif @rnd == 2
      @bg_image = '2.jpg'
      @bg_text = 'Red Sunset, Kafue National Park'
      @bg_username = 'Musonda Chibaye'
    elsif @rnd == 3
      @bg_image = '3.jpg'
      @bg_text = 'Victoria Falls Sunset'
      @bg_username = 'Vivian Chibaye'
    elsif @rnd == 4
      @bg_image = '4.jpg'
      @bg_text = 'Victoria Falls Bridge over Zambezi river.'
      @bg_username = 'Francis Chibaye'
    elsif @rnd == 5
      @bg_image = '5.jpg'
      @bg_text = 'Love yourself funtime'
      @bg_username = 'Vivian Chibaye'
    elsif @rnd == 6
      @bg_image = '6.jpg'
      @bg_text = 'Lake Tanganyika'
      @bg_username = 'Musonda Chibaye'
    elsif @rnd == 7
      @bg_image = '7.jpg'
      @bg_text = 'Zambia United'
      @bg_username = 'Patricia Chibaye'	
    elsif @rnd == 8
      @bg_image = '8.jpg'
      @bg_text = 'Zambezi Dream'
      @bg_username = 'Musonda Chibaye'
    else
      @bg_image = '9.jpg'
      @bg_text = 'Sunset view, Victoria Falls'
      @bg_username = 'Francis Chibaye'	  
    end
  end

  private
  MOBILE_BROWSERS = ["android", "ipod", "opera mini", "blackberry", "palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", "windows ce; smartphone;","windows ce; iemobile", "up.browser","up.link","mmp","symbian","smartphone", "midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]

  def detect_browser
    agent = request.headers["HTTP_USER_AGENT"].downcase
    MOBILE_BROWSERS.each do |m|
      if agent.match(m) && agent !~ /android|blackberry|iphone|ipad|opera mobi/
        request.format = :mobile
      elsif agent =~ /iphone/ && agent !~ /ipad|opera mini/
        request.format = :ios
      elsif agent =~ /opera\smobi|android|blackberry|windows\sce|windows\sphone|smartphone/
        request.format = :smartphone
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    bg_img
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    bg_img
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'Loudius'
    if page_title.empty?
      base_title
    else
      page_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_header.html.haml
.header
  .headerBg
    .container
      .header-left
        = link_to(image_tag 'logo-28px.png', size: '112x28')
      .header-right
        - if controller_name == 'sessions'
          = link_to 'Create Account', reg_path, class: 'btn-header'
        - else
          = link_to 'Log In', login_path, class: 'btn-header'

app/views/layouts/_header.ios.haml
#header
  #headerCenter
    = image_tag 'logo-28px.png', size: '112x28', class: 'logo-ios'

app/views/layouts/_header.mobile.haml
#header
  %table#top
    %tbody
      %tr
        %td.header-left
          -#= link_to(image_tag('', size: '28x28', class: 'logo'), root_path, class: 'brandmark')
          %span.title Welcome to Loudius
        %td.header-right

app/views/layouts/_header.smartphone.haml
#header
  #headerCenter
    = image_tag 'logo-28px.png', size: '112x28', class: 'logo-ios'

app/views/layouts/_shim.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
%meta{name: 'description', content: 'All the latest from friends and the world around you. What friend are talking about. Be discovered'}

app/views/layouts/_shim.ios.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
%meta{content: "True", name: "HandheldFriendly"}/
%meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", name: "viewport"}/
%meta{content: "{&quot;pwreset-iphone&quot;:true,&quot;android&quot;:true,&quot;email&quot;:true}", name: "loudius-redirect-srcs"}/
%meta{name: 'description', content: 'All the latest from friends and the world around you. What friend are talking about. Be discovered'}

app/views/layouts/_shim.mobile.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
%meta{content: "True", name: "HandheldFriendly"}/
%meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", name: "viewport"}/
%meta{content: "{&quot;pwreset-iphone&quot;:true,&quot;android&quot;:true,&quot;email&quot;:true}", name: "loudius-redirect-srcs"}/
%meta{name: 'description', content: 'All the latest from friends and the world around you. What friend are talking about. Be discovered'}

app/views/layouts/_shim.smartphone.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
%meta{content: "True", name: "HandheldFriendly"}/
%meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", name: "viewport"}/
%meta{content: "{&quot;pwreset-iphone&quot;:true,&quot;android&quot;:true,&quot;email&quot;:true}", name: "loudius-redirect-srcs"}/
%meta{name: 'description', content: 'All the latest from friends and the world around you. What friend are talking about. Be discovered'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'web/application', media: 'all',  |
      'data-turbolinks-track' => true                       |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .alert-messages
      .message
        .message-text
          Site still in development
          -#- flash.each do |key, value|
          -#  %div{class: "alert alert-#{key}"}= value
    = render 'layouts/header'
    #globalContainer
      = yield

app/views/layouts/application.ios.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'ios/application', media: 'all',  |
      'data-turbolinks-track' => true                       |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body.ios{ tabindex: 0 }
    #viewport
      #page
        = render 'layouts/header'
        .content#main
          #main_content
            .inner-content
              .alert-msg-ios
                %span.msg-text-ios
                  Site still in development
              = yield

app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'mobile/application', media: 'all',  |
      'data-turbolinks-track' => true                       |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .container
      = render 'layouts/header'
      #main_content
        = yield
      #footer
        .signup
          - if controller_name == 'sessions'
            .hint
              New to Loudius?
              = link_to 'Sign Up', '#'
            .fgt-pw= link_to 'Forgot your password?', '#'
          - else
            .hint
              Already have an account?
              = link_to 'Log In', '#'

app/views/layouts/application.smartphone.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'smartphone/application', media: 'all',  |
      'data-turbolinks-track' => true                       |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body.ios{ tabindex: 0 }
    #viewport
      #page
        = render 'layouts/header'
        .content#main
          #main_content
            .inner-content
              .alert-msg-ios
                %span.msg-text-ios
                  Site still in development
              = yield

app/views/shared/_auth.html.haml
.un-auth-bg
  = image_tag @bg_image
.un-auth-content
  #formWrapper
    - if controller_name == 'sessions'
      = render 'shared/forms/login'
    - else
      = render 'shared/forms/reg'
  .bg-username-and-text
    .username-text-wrapper
      .bg-img-text
        %p.text
          = @bg_text
        %p.username
          Image by
          %span= @bg_username

%footer.inline-list
  %ul	  
    %li
      Follow #{link_to '@francischibaye', 'http://www.twitter.com/francischibaye'} for development updates.
      %span.divider

app/views/shared/_auth.ios.haml
- if controller_name == 'sessions'
  = render 'shared/forms/login'
- else
  = render 'shared/forms/reg'
%footer
  %ul
    %li
      Follow #{link_to '@francischibaye', 'http://www.twitter.com/francischibaye'} for development updates.
      %span.divider

app/views/shared/_auth.mobile.haml
.header
  .hint
    Site still in Development
  - if controller_name == 'sessions'
    %h2 Log In
  - else
    %h2 Sign Up
.body
  - if controller_name == 'sessions'
    = render 'shared/forms/login'
  - else
    = render 'shared/forms/reg'
.footer
  .hint
    Follow #{link_to '@francischibaye', 'http://www.twitter.com/francischibaye'} for development updates.

app/views/shared/_auth.smartphone.haml
- if controller_name == 'sessions'
  = render 'shared/forms/login'
- else
  = render 'shared/forms/reg'
%footer
  %ul
    %li
      Follow #{link_to '@francischibaye', 'http://www.twitter.com/francischibaye'} for development updates.
      %span.divider

app/views/shared/forms/_login.html.haml
%form{class: 'form login-form'}
  %fieldset
    .fields
      %input{type: 'text', placeholder: 'Username or email', class: 'input login-input', disabled: :disabled}
      %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
  .footer
    %input{type: 'submit', value: 'Login', class: 'btn btn-common', disabled: :disabled}
    %input{type: 'submit', value: 'Forgot your password', class: 'link-login', disabled: :disabled}

app/views/shared/forms/_login.ios.haml
%form{class: 'form login-form'}
  .formview
    .fields
      %input{type: 'text', placeholder: 'Username or Phone number', class: 'input login-input', disabled: :disabled}
      %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
    .footer
      %input{type: 'submit', value: 'Login', class: 'btn', disabled: :disabled}
  #footer
    = link_to 'Create Account', reg_path, class: 'auth-link'
    .other-links
      %ul
        %li
          %span
            = link_to 'Forgot password?', '#'
            -#%span .
            -#= link_to 'Help Center', '#'

app/views/shared/forms/_login.mobile.haml
%form{class: 'form', id: 'login-form'}
  %span.m2-auth-token
    %fieldset
      .email
        %label
          Username or Phone number
        .input-wrapper
          %input{type: 'text', class: 'input', disabled: :disabled}
      .password
        %label
          Password
        .input-wrapper
          %input{type: 'password', class: 'input', disabled: :disabled}
    %span.w-button-bright.w-button-common
      %input{type: 'submit', value: 'Login', class: 'btn', disabled: :disabled}

app/views/shared/forms/_login.smartphone.haml
%form{class: 'form login-form'}
  .formview
    %fieldset
      %ul.list-group
        %li
          %label Username or Phone Number
          %input{type: 'text', placeholder: 'Username or Phone Number', class: 'input login-input', disabled: :disabled}
          %span.clearfield
        %li
          %label Password
          %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
          %span.clearfield

    %input{type: 'submit', value: 'Log In', class: 'btn-m', disabled: :disabled}
  #footer
    = link_to 'Create Account', reg_path, class: 'auth-link'
    .other-links
      %ul
        %li
          %span
            = link_to 'Forgot password?', '#'

app/views/shared/forms/_reg.html.haml
%form{class: 'form reg-form'}
  %fieldset
    %input{type: 'text', placeholder: 'Name', class: 'input name-input', disabled: :disabled}
    %input{type: 'text', placeholder: 'Email', class: 'input email-input', disabled: :disabled}
    %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
  .footer
    %input{type: 'submit', value: 'Create Account', class: 'btn btn-common btn-reg', disabled: :disabled}

app/views/shared/forms/_reg.ios.haml
%form{class: 'form reg-form'}
  .formview
    .fields
      %input{type: 'text', placeholder: 'Name', class: 'input login-input', disabled: :disabled}
      %input{type: 'text', placeholder: 'Phone number', class: 'input login-input', disabled: :disabled}
      %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
    .footer
      %input{type: 'submit', value: 'Create Account', class: 'btn', disabled: :disabled}
  #footer
    = link_to 'Log In', login_path, class: 'auth-link'

app/views/shared/forms/_reg.mobile.haml
%form{class: 'form', id: 'reg-form'}
  %span.m2-auth-token
    %fieldset
      .name
        %label
          Name
        .input-wrapper
          %input{type: 'text', class: 'input', disabled: :disabled}
      .email
        %label
          Phone number
        .input-wrapper
          %input{type: 'text', class: 'input', disabled: :disabled}
      .password
        %label
          Password
        .input-wrapper
          %input{type: 'password', class: 'input', disabled: :disabled}
    %span.w-button-bright.w-button-common
      %input{type: 'submit', value: 'Login', class: 'btn', disabled: :disabled}

app/views/shared/forms/_reg.smartphone.haml
%form{class: 'form reg-form'}
  .formview
    %fieldset
      %ul.list-group
        %li
          %label Name
          %input{type: 'text', placeholder: 'Name', class: 'input login-input', disabled: :disabled}
          %span.clearfield
        %li
          %label Phone Number
          %input{type: 'text', placeholder: 'Phone Number', class: 'input reg-login-input', disabled: :disabled}
          %span.clearfield
        %li
          %label Password
          %input{type: 'password', placeholder: 'Password', class: 'input pwd-input', disabled: :disabled}
          %span.clearfield

    %input{type: 'submit', value: 'Create Account', class: 'btn-m', disabled: :disabled}
  #footer
    = link_to 'Log In', login_path, class: 'auth-link'

app/views/users/new.html.haml
= render 'shared/auth'

app/views/users/new.ios.haml
= render 'shared/auth'

app/views/users/new.mobile.haml
= render 'shared/auth'

app/views/users/new.smartphone.haml
= render 'shared/auth'